name: publish

on: 
  push:
    tags:
      - v**
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/testgear-importer-allure
  
jobs:
  publish-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./testgear-importer-allure
        file: ./testgear-importer-allure/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.PAT }}
